<a href="https://colab.research.google.com/github/Rounak-Das-02/Custom-CNN-_Example/blob/main/Custom_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from keras.models import Sequential
from keras.layers import Dense , Flatten , MaxPooling2D , Dropout , Conv2D , BatchNormalization , GlobalAveragePooling2D
##from keras.applications.vgg16 import VGG16
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
from keras import models

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
model = Sequential()
IMAGE_SHAPE = [244,244,3]

In [5]:
##conv_base = VGG16(input_shape = IMAGE_SHAPE,weights = "imagenet" , include_top = False)

In [6]:
##model.add(conv_base)

In [7]:
my_model= models.Sequential()

# Add first convolutional block
my_model.add(Conv2D(16, (3, 3), activation='relu', padding='same', 
                    input_shape=(178,218,3)))
my_model.add(MaxPooling2D((2, 2), padding='same'))

# second block
my_model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
my_model.add(MaxPooling2D((2, 2), padding='same'))
# third block
my_model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
my_model.add(MaxPooling2D((2, 2), padding='same'))
# fourth block
my_model.add(Conv2D(128, (3, 3), activation='relu', padding='same'))
my_model.add(MaxPooling2D((2, 2), padding='same'))

# global average pooling
my_model.add(GlobalAveragePooling2D())
# fully connected layer
my_model.add(Dense(64, activation='relu'))
my_model.add(BatchNormalization())
# make predictions
my_model.add(Dense(2, activation='sigmoid'))

In [8]:
my_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 178, 218, 16)      448       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 89, 109, 16)       0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 89, 109, 32)       4640      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 45, 55, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 45, 55, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 23, 28, 64)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 23, 28, 128)      

In [9]:
my_model.compile(optimizer = "adam" , loss = "categorical_crossentropy" , metrics=["accuracy"])

In [10]:
!git clone https://github.com/laxmimerit/dog-cat-full-dataset.git

Cloning into 'dog-cat-full-dataset'...
remote: Enumerating objects: 25027, done.
remote: Total 25027 (delta 0), reused 0 (delta 0), pack-reused 25027
Receiving objects: 100% (25027/25027), 541.62 MiB | 43.35 MiB/s, done.
Resolving deltas: 100% (5/5), done.
Checking out files: 100% (25001/25001), done.


In [11]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory(r'/content/dog-cat-full-dataset/data/train',
                                                 target_size = (224, 224),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

test_set = test_datagen.flow_from_directory(r'/content/dog-cat-full-dataset/data/test',
                                            target_size = (224, 224),
                                            batch_size = 32,
                                            class_mode = 'categorical')


Found 20000 images belonging to 2 classes.
Found 5000 images belonging to 2 classes.


In [12]:
my_model.fit_generator(training_set , steps_per_epoch=625 , validation_data=test_set , epochs = 5 , validation_steps=32)

Instructions for updating:
Please use Model.fit, which supports generators.
Epoch 1/5
625/625 [==============================] - 239s 383ms/step - loss: 0.6253 - accuracy: 0.6502 - val_loss: 0.6456 - val_accuracy: 0.5771
Epoch 2/5
625/625 [==============================] - 235s 377ms/step - loss: 0.5608 - accuracy: 0.7114 - val_loss: 0.6800 - val_accuracy: 0.6738
Epoch 3/5
625/625 [==============================] - 233s 372ms/step - loss: 0.5143 - accuracy: 0.7485 - val_loss: 0.5660 - val_accuracy: 0.6924
Epoch 4/5
625/625 [==============================] - 237s 379ms/step - loss: 0.4870 - accuracy: 0.7643 - val_loss: 0.4746 - val_accuracy: 0.7744
Epoch 5/5
625/625 [==============================] - 240s 384ms/step - loss: 0.4601 - accuracy: 0.7846 - val_loss: 0.4761 - val_accuracy: 0.7773


In [13]:
import tensorflow as tf
from keras.models import load_model

In [14]:
my_model.save("Custom CNN DogsVsCats.h5")

In [15]:
model = load_model("/content/Custom CNN DogsVsCats.h5")

In [38]:
import cv2
from keras.preprocessing import image

In [54]:
img = image.load_img("/content/11900.jpg" , target_size= (178 , 218))

In [55]:
img = image.img_to_array(img)

In [56]:
img = np.expand_dims(img , axis = 0)

In [69]:
prediction = model.predict([img])

In [70]:
print(prediction)

[[0. 1.]]


In [64]:
prob = model.predict_proba([img/255.0])

In [60]:
probability = model.predict_classes([img])

In [61]:
probability

array([1])

In [65]:
print(prob)

[[0.13274394 0.56843895]]
